[build]
  command = "cd web && npm install && npm run build"
  publish = "web/dist"

# Serve built assets without SPA rewrite
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = true

# API functions
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Public product pages - serve separate HTML file
[[redirects]]
  from = "/public/product/*"
  to = "/public-product.html"
  status = 200
  force = true

# Catch-all SPA route for Vue app (main system)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000, immutable"


[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    Cache-Control = "no-cache, no-store, must-revalidate"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"

