[build]
  command = "cd web && npm ci && npm run build"
  publish = "web/dist"

# Serve built assets without SPA rewrite
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = true

# Send root to Expo app index
[[redirects]]
  from = "/"
  to = "/app/index.html"
  status = 200
  force = true

# Handle /app without trailing slash
[[redirects]]
  from = "/app"
  to = "/app/index.html"
  status = 200
  force = true


# Catch-all SPA route last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000, immutable"


[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    Cache-Control = "no-cache, no-store, must-revalidate"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"

