[build]
  command = "npm ci && npm run build"
  publish = "dist"

# Serve built assets without SPA rewrite
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = true

# Catch-all SPA route for Vue app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    Cache-Control = "no-cache, no-store, must-revalidate"

[build.environment]
  NODE_VERSION = "20"

# Note: Functions não estarão disponíveis nesta configuração
# Para usar Google Sheets API, você precisará configurar as functions separadamente
